apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: <your-cart-ecr-image>
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: cart-config