apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 857874856616.dkr.ecr.ap-south-1.amazonaws.com/product-service:1abaed34999749423c85eb17cf86d28552281763
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret