apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: dev
data:
  AWS_REGION: ap-south-1
  NOTIFICATION_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/857874856616/notification-queue